package com.lingframe.plugin.storage.proxy;

import com.lingframe.api.context.PluginContextHolder;
import com.lingframe.api.exception.PermissionDeniedException;
import com.lingframe.api.security.AccessType;
import com.lingframe.api.security.PermissionService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.sql.*;

@Slf4j
@RequiredArgsConstructor
public class LingPreparedStatementProxy implements PreparedStatement {

    private final PreparedStatement target;
    private final PermissionService permissionService;
    private final String sql; // 预编译的 SQL

    // --- 核心鉴权逻辑 ---
    private void checkPermission() throws SQLException {
        // 1. 获取当前调用者（业务插件ID）
        // 这里依赖我们在 Runtime 层实现的 ThreadLocal Holder
        String callerPluginId = PluginContextHolder.get();
        if (callerPluginId == null) {
            // 如果拿不到 ID，可能是 Core 自身在调用，或者某些特殊情况，默认放行或严格拒绝
            // log.debug("No caller plugin id found, skipping check.");
            return;
        }

        // 2. 简单的 SQL 解析 (生产环境请用 JSqlParser)
        String trimmedSql = sql.trim().toUpperCase();
        AccessType accessType = AccessType.EXECUTE; // 默认
        if (trimmedSql.startsWith("SELECT")) {
            accessType = AccessType.READ;
        } else if (trimmedSql.startsWith("INSERT") || trimmedSql.startsWith("UPDATE") || trimmedSql.startsWith("DELETE")) {
            accessType = AccessType.WRITE;
        }

        // 3. 调用 Core 进行鉴权
        boolean allowed = permissionService.isAllowed(callerPluginId, "storage:sql", accessType);

        // 4. 上报审计 (异步)
        permissionService.audit(callerPluginId, "storage:sql", sql, allowed);

        if (!allowed) {
            throw new SQLException(new PermissionDeniedException(
                    "Plugin [" + callerPluginId + "] denied access to SQL: " + sql));
        }
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        checkPermission();
        return target.executeQuery();
    }

    @Override
    public int executeUpdate() throws SQLException {
        checkPermission();
        return target.executeUpdate();
    }

    @Override
    public boolean execute() throws SQLException {
        checkPermission();
        return target.execute();
    }

    // --- 同样，省略其余上百个 Setter/Getter 的委托方法，IDE 生成即可 ---
    // 下面仅示例几个关键的，其他的必须补全
    @Override public void close() throws SQLException { target.close(); }
    @Override public void setString(int parameterIndex, String x) throws SQLException { target.setString(parameterIndex, x); }
    @Override public void setInt(int parameterIndex, int x) throws SQLException { target.setInt(parameterIndex, x); }
    @Override public void setLong(int parameterIndex, long x) throws SQLException { target.setLong(parameterIndex, x); }
    // ... 请务必补全所有 setXxx 方法
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return target.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return target.isWrapperFor(iface); }
    // ...
    // 省略几百行... (实际开发请用 IDE Generate Delegate Methods)
    @Override public ResultSet getResultSet() throws SQLException { return target.getResultSet(); }
    @Override public int getUpdateCount() throws SQLException { return target.getUpdateCount(); }
    @Override public boolean getMoreResults() throws SQLException { return target.getMoreResults(); }
    @Override public void setFetchDirection(int direction) throws SQLException { target.setFetchDirection(direction); }
    @Override public int getFetchDirection() throws SQLException { return target.getFetchDirection(); }
    @Override public void setFetchSize(int rows) throws SQLException { target.setFetchSize(rows); }
    @Override public int getFetchSize() throws SQLException { return target.getFetchSize(); }
    @Override public int getResultSetConcurrency() throws SQLException { return target.getResultSetConcurrency(); }
    @Override public int getResultSetType() throws SQLException { return target.getResultSetType(); }
    @Override public void addBatch(String sql) throws SQLException { target.addBatch(sql); }
    @Override public void clearBatch() throws SQLException { target.clearBatch(); }
    @Override public int[] executeBatch() throws SQLException { return target.executeBatch(); }
    @Override public Connection getConnection() throws SQLException { return target.getConnection(); }
    @Override public boolean getMoreResults(int current) throws SQLException { return target.getMoreResults(current); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { return target.getGeneratedKeys(); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return target.executeUpdate(sql, autoGeneratedKeys); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return target.executeUpdate(sql, columnIndexes); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return target.executeUpdate(sql, columnNames); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return target.execute(sql, autoGeneratedKeys); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return target.execute(sql, columnIndexes); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return target.execute(sql, columnNames); }
    @Override public int getResultSetHoldability() throws SQLException { return target.getResultSetHoldability(); }
    @Override public boolean isClosed() throws SQLException { return target.isClosed(); }
    @Override public void setPoolable(boolean poolable) throws SQLException { target.setPoolable(poolable); }
    @Override public boolean isPoolable() throws SQLException { return target.isPoolable(); }
    @Override public void closeOnCompletion() throws SQLException { target.closeOnCompletion(); }
    @Override public boolean isCloseOnCompletion() throws SQLException { return target.isCloseOnCompletion(); }
    @Override public int executeUpdate(String sql) throws SQLException { return target.executeUpdate(sql); }
    @Override public boolean execute(String sql) throws SQLException { return target.execute(sql); }
    @Override public ResultSet executeQuery(String sql) throws SQLException { return target.executeQuery(sql); }
    @Override public int getMaxFieldSize() throws SQLException { return target.getMaxFieldSize(); }
    @Override public void setMaxFieldSize(int max) throws SQLException { target.setMaxFieldSize(max); }
    @Override public int getMaxRows() throws SQLException { return target.getMaxRows(); }
    @Override public void setMaxRows(int max) throws SQLException { target.setMaxRows(max); }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { target.setEscapeProcessing(enable); }
    @Override public int getQueryTimeout() throws SQLException { return target.getQueryTimeout(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { target.setQueryTimeout(seconds); }
    @Override public void cancel() throws SQLException { target.cancel(); }
    @Override public SQLWarning getWarnings() throws SQLException { return target.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { target.clearWarnings(); }
    @Override public void setCursorName(String name) throws SQLException { target.setCursorName(name); }
    @Override public void setNull(int parameterIndex, int sqlType) throws SQLException { target.setNull(parameterIndex, sqlType); }
    @Override public void setBoolean(int parameterIndex, boolean x) throws SQLException { target.setBoolean(parameterIndex, x); }
    @Override public void setByte(int parameterIndex, byte x) throws SQLException { target.setByte(parameterIndex, x); }
    @Override public void setShort(int parameterIndex, short x) throws SQLException { target.setShort(parameterIndex, x); }
    @Override public void setFloat(int parameterIndex, float x) throws SQLException { target.setFloat(parameterIndex, x); }
    @Override public void setDouble(int parameterIndex, double x) throws SQLException { target.setDouble(parameterIndex, x); }
    @Override public void setBigDecimal(int parameterIndex, java.math.BigDecimal x) throws SQLException { target.setBigDecimal(parameterIndex, x); }
    @Override public void setBytes(int parameterIndex, byte[] x) throws SQLException { target.setBytes(parameterIndex, x); }
    @Override public void setDate(int parameterIndex, java.sql.Date x) throws SQLException { target.setDate(parameterIndex, x); }
    @Override public void setTime(int parameterIndex, java.sql.Time x) throws SQLException { target.setTime(parameterIndex, x); }
    @Override public void setTimestamp(int parameterIndex, java.sql.Timestamp x) throws SQLException { target.setTimestamp(parameterIndex, x); }
    @Override public void setAsciiStream(int parameterIndex, java.io.InputStream x, int length) throws SQLException { target.setAsciiStream(parameterIndex, x, length); }
    @Override public void setUnicodeStream(int parameterIndex, java.io.InputStream x, int length) throws SQLException { target.setUnicodeStream(parameterIndex, x, length); }
    @Override public void setBinaryStream(int parameterIndex, java.io.InputStream x, int length) throws SQLException { target.setBinaryStream(parameterIndex, x, length); }
    @Override public void clearParameters() throws SQLException { target.clearParameters(); }
    @Override public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException { target.setObject(parameterIndex, x, targetSqlType); }
    @Override public void setObject(int parameterIndex, Object x) throws SQLException { target.setObject(parameterIndex, x); }
    @Override public void addBatch() throws SQLException { target.addBatch(); }
    @Override public void setCharacterStream(int parameterIndex, java.io.Reader reader, int length) throws SQLException { target.setCharacterStream(parameterIndex, reader, length); }
    @Override public void setRef(int parameterIndex, Ref x) throws SQLException { target.setRef(parameterIndex, x); }
    @Override public void setBlob(int parameterIndex, Blob x) throws SQLException { target.setBlob(parameterIndex, x); }
    @Override public void setClob(int parameterIndex, Clob x) throws SQLException { target.setClob(parameterIndex, x); }
    @Override public void setArray(int parameterIndex, Array x) throws SQLException { target.setArray(parameterIndex, x); }
    @Override public ResultSetMetaData getMetaData() throws SQLException { return target.getMetaData(); }
    @Override public void setDate(int parameterIndex, java.sql.Date x, java.util.Calendar cal) throws SQLException { target.setDate(parameterIndex, x, cal); }
    @Override public void setTime(int parameterIndex, java.sql.Time x, java.util.Calendar cal) throws SQLException { target.setTime(parameterIndex, x, cal); }
    @Override public void setTimestamp(int parameterIndex, java.sql.Timestamp x, java.util.Calendar cal) throws SQLException { target.setTimestamp(parameterIndex, x, cal); }
    @Override public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException { target.setNull(parameterIndex, sqlType, typeName); }
    @Override public void setURL(int parameterIndex, java.net.URL x) throws SQLException { target.setURL(parameterIndex, x); }
    @Override public java.sql.ParameterMetaData getParameterMetaData() throws SQLException { return target.getParameterMetaData(); }
    @Override public void setRowId(int parameterIndex, RowId x) throws SQLException { target.setRowId(parameterIndex, x); }
    @Override public void setNString(int parameterIndex, String value) throws SQLException { target.setNString(parameterIndex, value); }
    @Override public void setNCharacterStream(int parameterIndex, java.io.Reader value, long length) throws SQLException { target.setNCharacterStream(parameterIndex, value, length); }
    @Override public void setNClob(int parameterIndex, NClob value) throws SQLException { target.setNClob(parameterIndex, value); }
    @Override public void setClob(int parameterIndex, java.io.Reader reader, long length) throws SQLException { target.setClob(parameterIndex, reader, length); }
    @Override public void setBlob(int parameterIndex, java.io.InputStream inputStream, long length) throws SQLException { target.setBlob(parameterIndex, inputStream, length); }
    @Override public void setNClob(int parameterIndex, java.io.Reader reader, long length) throws SQLException { target.setNClob(parameterIndex, reader, length); }
    @Override public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException { target.setSQLXML(parameterIndex, xmlObject); }
    @Override public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException { target.setObject(parameterIndex, x, targetSqlType, scaleOrLength); }
    @Override public void setAsciiStream(int parameterIndex, java.io.InputStream x, long length) throws SQLException { target.setAsciiStream(parameterIndex, x, length); }
    @Override public void setBinaryStream(int parameterIndex, java.io.InputStream x, long length) throws SQLException { target.setBinaryStream(parameterIndex, x, length); }
    @Override public void setCharacterStream(int parameterIndex, java.io.Reader reader, long length) throws SQLException { target.setCharacterStream(parameterIndex, reader, length); }
    @Override public void setAsciiStream(int parameterIndex, java.io.InputStream x) throws SQLException { target.setAsciiStream(parameterIndex, x); }
    @Override public void setBinaryStream(int parameterIndex, java.io.InputStream x) throws SQLException { target.setBinaryStream(parameterIndex, x); }
    @Override public void setCharacterStream(int parameterIndex, java.io.Reader reader) throws SQLException { target.setCharacterStream(parameterIndex, reader); }
    @Override public void setNCharacterStream(int parameterIndex, java.io.Reader value) throws SQLException { target.setNCharacterStream(parameterIndex, value); }
    @Override public void setClob(int parameterIndex, java.io.Reader reader) throws SQLException { target.setClob(parameterIndex, reader); }
    @Override public void setBlob(int parameterIndex, java.io.InputStream inputStream) throws SQLException { target.setBlob(parameterIndex, inputStream); }
    @Override public void setNClob(int parameterIndex, java.io.Reader reader) throws SQLException { target.setNClob(parameterIndex, reader); }
}