# --- 基础元数据 (直接在根节点) ---
id: user-plugin
version: 1.0.0
provider: "LingFrame"
description: "用户插件"
mainClass: "com.lingframe.example.user.UserPlugin"

# --- 治理配置 ---
governance:
    # ACL 入站规则 (StandardGovernancePolicyProvider 使用)
    permissions: []

    # 插件能力申请 (PluginManager 使用)
    capabilities:
      - capability: "storage:sql"      # Capability Resource
        accessType: "READ"             # Access Type
      - capability: "cache:spring"
        accessType: "WRITE"

# --- 自定义扩展/依赖 (对应 Map<String, Object> properties) ---
properties:
  mark: "test"
