plugin:
  id: user-plugin
  version: 1.0.0
  permissions:
    - capability: "storage:sql"
      access: "READ"
    - capability: "cache:redis"
      access: "WRITE"
  dependencies:
    - id: "base-service"
      minVersion: "1.0.0"