# --- 基础元数据 (直接在根节点) ---
id: order-plugin
version: 1.0.0
provider: "LingFrame"
description: "订单插件"
mainClass: "com.lingframe.example.plugin.order.OrderPlugin"

dependencies:
  - id: "user-plugin"
    minVersion: "1.0.0"

# --- 治理配置 (对应 private GovernancePolicy governance) ---
governance:
  permissions:
    # 对应 GovernancePolicy.PermissionRule 的字段
    - methodPattern: "storage:sql"   # 原 capability
      permissionId: "READ"           # 原 access
    - methodPattern: "cache:redis"
      permissionId: "WRITE"

# --- 自定义扩展/依赖 (对应 Map<String, Object> properties) ---
properties:
  mark: "test"
