# --- 基础元数据 (直接在根节点) ---
id: order-plugin
version: 1.0.0
provider: "LingFrame"
description: "订单插件"
mainClass: "com.lingframe.example.order.OrderApplication"

# --- 治理配置 ---
governance:
  # ACL 入站规则 (StandardGovernancePolicyProvider 使用)
  permissions: []

  # 插件能力申请 (PluginManager 使用)
  capabilities:
    - capability: "storage:sql"
      accessType: "WRITE"      # 需要读写权限
    - capability: "cache:local"
      accessType: "WRITE"      # 使用本地缓存，与 Dashboard 对齐

# --- 自定义扩展/依赖 (对应 Map<String, Object> properties) ---
properties:
  mark: "test"

